version: 2.1

jobs:
  lint-and-unit-test:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0
    steps:
      - checkout
      - run:
          command: pyenv virtualenv 3.9.4 venv && pyenv global venv
      - run:
          command: pip install -r requirements.txt -r requirements-dev.txt
      - run:
          command: pre-commit run --all-files --show-diff-on-failure
      - run:
          command: python -m pytest tests/ -s -v

workflows:
  test:
    jobs:
      - lint-and-unit-test
